@extends('layouts.storefront')
@section('title',($currentCategory?->title ?? 'Watches').' | WristWatch')
@section('content')
<div class="ww-container"><div class="ww-catalog-banner"><img src="{{ asset('storefront/images/hero-3.jpg') }}" alt="Watch collection"></div><div class="ww-page-title"><h1>{{ $currentCategory?->title ?? 'Watches' }}</h1><p>{{ strip_tags($currentCategory?->description ?? 'Nam tempus turpis at metus scelerisque placerat nulla deumantos sollicitudin delos felis. Discover our collection of timeless watches, selected for every occasion.') }}</p></div></div>
@if($currentCategory && $currentCategory->children->count())<div class="ww-subcategories">@foreach($currentCategory->children as $child)<a href="{{ route('products.category',$child->slug) }}">{{ $child->title }}</a>@endforeach</div>@endif
<div class="ww-container ww-catalog"><aside class="ww-sidebar" id="ww-filters"><h3>Shop By</h3><form method="get" action="{{ url()->current() }}">@if(request('search'))<input type="hidden" name="search" value="{{ request('search') }}">@endif<input type="hidden" name="sort" value="{{ request('sort','newest') }}">
<details open><summary>Categories</summary>@foreach($categories as $filterCategory)<label><input type="checkbox" name="categories[]" value="{{ $filterCategory->slug }}" @checked(in_array($filterCategory->slug,(array)request('categories',[])))>{{ $filterCategory->title }}</label>@endforeach</details>
<details open><summary>Price</summary><div class="ww-price-filter"><input type="number" name="min_price" min="0" step="0.01" value="{{ request('min_price') }}" placeholder="Min" aria-label="Minimum price"><input type="number" name="max_price" min="0" step="0.01" value="{{ request('max_price') }}" placeholder="Max" aria-label="Maximum price"></div></details>
<details open><summary>Availability</summary>@foreach(['in_stock'=>'In Stock','out_of_stock'=>'Out of Stock'] as $key=>$label)<label><input type="checkbox" name="availability[]" value="{{ $key }}" @checked(in_array($key,(array)request('availability',[])))>{{ $label }}</label>@endforeach</details>
@foreach($filterOptions as $option)<details><summary>{{ $option->name }}</summary>@foreach($option->values as $value)<label><input type="checkbox" name="options[{{ $option->id }}][]" value="{{ $value->id }}" @checked(in_array($value->id,(array)request('options.'.$option->id,[])))>{{ $value->value }}</label>@endforeach</details>@endforeach
<button class="ww-button">Apply Filters</button><a href="{{ url()->current() }}">Clear all</a></form></aside>
<section><button class="ww-filter-toggle" data-toggle="ww-filters" aria-expanded="false">☷ &nbsp; Show Sidebar</button><form class="ww-toolbar" method="get">@foreach(request()->except('sort','page','per_page') as $name=>$value)@if(!is_array($value))<input type="hidden" name="{{ $name }}" value="{{ $value }}">@else @foreach($value as $key=>$item)@if(!is_array($item))<input type="hidden" name="{{ $name }}[]" value="{{ $item }}">@else @foreach($item as $nested)<input type="hidden" name="{{ $name }}[{{ $key }}][]" value="{{ $nested }}">@endforeach @endif @endforeach @endif @endforeach<div>View As <button type="button" class="ww-view-switch" data-grid="grid" aria-label="Grid view">▦</button><button type="button" class="ww-view-switch" data-grid="list" aria-label="List view">≡</button></div><label>Show <select name="per_page" data-submit>@foreach([12,24,36] as $perPage)<option value="{{ $perPage }}" @selected((int)request('per_page',12)===$perPage)>{{ $perPage }} items per page</option>@endforeach</select></label><label>Sort By <select name="sort" data-submit>@foreach(['newest'=>'Newest Items','popular'=>'Featured Items','best_selling'=>'Best Selling','price_low'=>'Price: Low to High','price_high'=>'Price: High to Low','rating'=>'Top Rated','discount'=>'Best Discount'] as $key=>$label)<option value="{{ $key }}" @selected(request('sort','newest')===$key)>{{ $label }}</option>@endforeach</select></label></form>
@if(request('search'))<p>Search results for “{{ request('search') }}”</p>@endif<div class="ww-products" id="ww-catalog-grid">@forelse($products as $product)@include('storefront.product-card')@empty<div class="ww-empty"><h2>No products found</h2><p>Try another search or adjust your filters.</p><a class="ww-button" href="{{ route('products.index') }}">View All Watches</a></div>@endforelse</div><div class="ww-pagination">{{ $products->links() }}</div></section></div>
@endsection

