@php($wwCategories = $wwCategories ?? \App\Models\ProductCategory::whereNull('parent_id')->whereHas('products', fn($q)=>$q->where('status','active'))->orderByRaw("CASE slug WHEN 'new-releases' THEN 0 WHEN 'mens' THEN 1 WHEN 'womens' THEN 2 WHEN 'jewelry' THEN 3 WHEN 'accessories' THEN 4 ELSE 5 END")->with('children')->get())
<div class="ww-announcement">Free Shipping on all Orders. No Minimum Purchases Required*</div>
<header class="ww-header">
<div class="ww-header-top ww-container"><div class="ww-contact-mini">Contact us <a href="{{ route('contact-page') }}">Customer service</a></div><a class="ww-logo" href="{{ route('home-page') }}">WRIST<span class="ww-hourglass">⌛</span>WATCH<small>THE ART OF TIME</small></a><div class="ww-header-actions"><a href="{{ route('login') }}" aria-label="Account">@include('storefront.icon',['icon'=>'user'])<span>Account</span></a><a href="{{ route('cart.index') }}" aria-label="Shopping cart">@include('storefront.icon',['icon'=>'cart'])<span>Cart</span><b class="ww-cart-count">{{ collect(session('cart',[]))->sum('quantity') }}</b></a></div></div>
<div class="ww-mobile-head"><button data-open="ww-menu" aria-label="Open navigation">@include('storefront.icon',['icon'=>'menu'])</button><button data-open="ww-search" aria-label="Search watches">@include('storefront.icon',['icon'=>'search'])</button><a class="ww-logo" href="{{ route('home-page') }}">WRISTWATCH</a><a href="{{ route('login') }}" aria-label="Account">@include('storefront.icon',['icon'=>'user'])</a><a href="{{ route('cart.index') }}" aria-label="Shopping cart">@include('storefront.icon',['icon'=>'cart'])<b class="ww-cart-count">{{ collect(session('cart',[]))->sum('quantity') }}</b></a></div>
<nav class="ww-nav ww-container" aria-label="Main navigation"><div class="ww-nav-links"><a href="{{ route('products.index',['sort'=>'newest']) }}">New Releases</a>@foreach($wwCategories->where('slug','!=','new-releases')->take(5) as $navCategory)<div class="ww-nav-item"><a href="{{ route('products.category',$navCategory->slug) }}">{{ $navCategory->title }}</a>@if($navCategory->children->count())<div class="ww-dropdown">@foreach($navCategory->children as $child)<a href="{{ route('products.category',$child->slug) }}">{{ $child->title }}</a>@endforeach</div>@endif</div>@endforeach<a href="{{ route('products.index') }}">Watches</a><a href="{{ route('about-page') }}">About Us</a><a href="{{ route('blogs-page') }}">Blog</a><a href="{{ route('contact-page') }}">Contact</a></div><button data-open="ww-search" aria-label="Search">@include('storefront.icon',['icon'=>'search'])</button></nav>
</header>
<dialog id="ww-menu" class="ww-drawer"><button class="ww-close" data-close-dialog aria-label="Close navigation">×</button><h2>WristWatch</h2><a href="{{ route('home-page') }}">Home</a><a href="{{ route('products.index') }}">New Releases</a>@foreach($wwCategories as $navCategory)<details><summary><a href="{{ route('products.category',$navCategory->slug) }}">{{ $navCategory->title }}</a></summary>@foreach($navCategory->children as $child)<a href="{{ route('products.category',$child->slug) }}">{{ $child->title }}</a>@endforeach</details>@endforeach<a href="{{ route('products.index') }}">All Watches</a><a href="{{ route('about-page') }}">About Us</a><a href="{{ route('blogs-page') }}">Blog</a><a href="{{ route('categories-page') }}">Blog Categories</a><a href="{{ route('contact-page') }}">Contact Us</a><a href="{{ route('favorites.index') }}">Wish Lists</a><a href="{{ route('login') }}">My Account</a></dialog>
<dialog id="ww-search" class="ww-search-dialog"><button class="ww-close" data-close-dialog aria-label="Close search">×</button><h2>Search our collection</h2><form action="{{ route('products.index') }}" method="get"><label class="ww-sr" for="ww-search-input">Search watches</label><input id="ww-search-input" name="search" placeholder="Search watches…" required maxlength="150"><button class="ww-button">Search</button></form><p>Discover luxury watches, chronographs and timeless classics.</p></dialog>

