@extends('layouts.storefront')
@section('title','WristWatch | Luxury Watches')
@section('content')
<section class="ww-hero" aria-label="Featured collections" aria-roledescription="carousel">
@foreach([['Cosmopolis','hero-1.jpg'],['Milancelos','hero-2.jpg'],['Special Offers','hero-3.jpg']] as $slide)
<div class="ww-slide ww-slide-dark" data-slide @if(!$loop->first) hidden @endif><img src="{{ asset('storefront/images/'.$slide[1]) }}" alt="{{ $slide[0] }} watch collection" @if($loop->first) fetchpriority="high" @else loading="lazy" @endif><div class="ww-slide-copy"><h1>{{ $slide[0] }}</h1><p>Quisquemos sodales suscipit tortor ditaemcos milancelos condimentum de cosmo lacus meleifend blanditos.</p><a class="ww-button ww-button-outline" href="{{ route('products.index') }}">{{ $loop->last ? 'Shop Mens' : 'Shop This Collection' }}</a></div></div>
@endforeach
<button class="ww-hero-arrow prev" data-slide-step="-1" aria-label="Previous slide">‹</button><button class="ww-hero-arrow next" data-slide-step="1" aria-label="Next slide">›</button><div class="ww-hero-dots">@for($i=0;$i<3;$i++)<button data-slide-index="{{ $i }}" aria-label="Show slide {{ $i+1 }}" aria-pressed="{{ $i===0?'true':'false' }}"></button>@endfor</div></section>
<div class="ww-container ww-benefits">@foreach([['truck','Free Shipping Worldwide'],['return','Free In-store Returns'],['shield','Genuine Product Guarantee'],['lock','100% Secure Shopping']] as $benefit)<div>@include('storefront.icon',['icon'=>$benefit[0]]){{ $benefit[1] }}</div>@endforeach</div>
<section class="ww-container ww-section"><h2 class="ww-section-title">Best Sellers</h2><div class="ww-products">@forelse($latestProducts->take(4) as $product)@include('storefront.product-card')@empty<div class="ww-empty">Our new watch collection is coming soon.</div>@endforelse</div></section>
<section class="ww-container ww-collection-pair">@foreach([['Womens Watches','womens.jpg','womens'],['Mens Watches','mens.jpg','mens']] as $collection)<a class="ww-collection" href="{{ url('product-category/'.$collection[2]) }}"><img src="{{ asset('storefront/images/'.$collection[1]) }}" alt="{{ $collection[0] }}" loading="lazy"><div class="ww-collection-copy"><h2>{{ $collection[0] }}</h2><span class="ww-button ww-button-outline">Shop Now</span></div></a>@endforeach</section>
<section class="ww-container ww-section"><h2 class="ww-section-title">Featured Products</h2><div class="ww-products">@forelse(($popularProducts->isNotEmpty()?$popularProducts:$latestProducts)->take(4) as $product)@include('storefront.product-card')@empty<div class="ww-empty">Explore our upcoming collections.</div>@endforelse</div></section>
<section class="ww-editorial"><div class="ww-container"><h2 class="ww-section-title">#Custom Block</h2><p>Nullam aliquet vestibulum augue non varius. Cras nec congue elit duis tristique vel ante nec aliquam. Praesent urna tellus laoreet eu tellus ullamcorper fermentum facilisis erat. Suspendisse tellus erat saliquam vel loremous a posuere tincidunt melitos.</p><div class="ww-editorial-feature"><img src="{{ asset('storefront/images/mens.jpg') }}" alt="Editor's watch collection" loading="lazy"><div><h3>EDITOR’S PICKS</h3><h2>Milancelos</h2><p>Quisquemos sodales suscipit tortor ditaemcos milancelos condimentum de cosmo lacus meleifend blanditos.</p><a class="ww-button ww-button-outline" href="{{ route('products.index') }}">Shop This Collection</a></div></div></div></section>
<section class="ww-container ww-section ww-brands" aria-label="Watch brands">@for($i=1;$i<=4;$i++)<a href="{{ route('products.index') }}"><img src="{{ asset('storefront/images/brand-'.$i.'.jpg') }}" alt="Watch brand {{ $i }}" loading="lazy"></a>@endfor</section>
<section><h2 class="ww-section-title">#WristWatch on Instagram</h2><div class="ww-instagram">@for($i=1;$i<=4;$i++)<a href="{{ route('products.index') }}"><img src="{{ asset('storefront/images/instagram-gallery-'.$i.'.jpg') }}" alt="WristWatch inspiration {{ $i }}" loading="lazy"></a>@endfor</div></section>
@include('storefront.newsletter-popup')
@endsection
