@extends('layouts.storefront')
@section('title',$product->meta_title ?: $product->title.' | WristWatch')
@section('content')
@php($media=app(\App\Services\PublicMediaService::class))
@php($money=app(\App\Services\StoreSettingsService::class))
@php($price=$product->sale_price !== null && $product->sale_price < $product->regular_price ? $product->sale_price : $product->regular_price)
<div class="ww-container"><div class="ww-breadcrumb"><a href="{{ route('home-page') }}">Home</a> / <a href="{{ route('products.index') }}">Watches</a> / {{ $product->title }}</div><section class="ww-detail"><div><img id="ww-main-product-image" class="ww-main-image" src="{{ $media->productImage($product) }}" alt="{{ $product->title }}"><div class="ww-thumbs"><button data-product-image="{{ $media->productImage($product) }}" aria-label="Show main product image"><img src="{{ $media->productImage($product) }}" alt="Main view"></button>@foreach($product->images as $image)<button data-product-image="{{ $media->url($image->image) }}" aria-label="Show product image {{ $loop->iteration }}"><img src="{{ $media->url($image->image) }}" alt="{{ $product->title }} view {{ $loop->iteration }}" loading="lazy"></button>@endforeach</div><div class="ww-detail-services">@foreach([['truck','Free Shipping Worldwide'],['return','Free In-store Returns'],['shield','Genuine Product Guarantee'],['lock','Secure Shopping']] as $benefit)<div>@include('storefront.icon',['icon'=>$benefit[0]]){{ $benefit[1] }}</div>@endforeach</div></div><div class="ww-detail-info"><p class="ww-product-brand">WRISTWATCH</p><h1>{{ $product->title }}</h1><div class="ww-rating">{{ str_repeat('★', (int)round($product->approved_reviews_avg_rating ?? 0)) }}{{ str_repeat('☆', 5-(int)round($product->approved_reviews_avg_rating ?? 0)) }} <a href="#ww-reviews" data-tab-link="reviews">{{ $product->approved_reviews_count }} Reviews &nbsp; Write A Review</a></div><dl><dt>SKU:</dt><dd data-sku>{{ $product->sku ?: 'N/A' }}</dd><dt>Condition:</dt><dd>New</dd><dt>Availability:</dt><dd>{{ $product->variants->isNotEmpty()?'Choose options':($money->available((int)$product->stock)>0?'In Stock':'Out of Stock') }}</dd></dl><div class="ww-detail-price">@if($price < $product->regular_price)<del>{{ $money->money((float)$product->regular_price) }}</del>@endif<span data-product-price>{{ $money->money((float)$price) }}</span></div><p>{{ strip_tags($product->short_description ?? '') }}</p>@include('storefront.product-form')<form action="{{ route('favorite.toggle') }}" method="post">@csrf<input type="hidden" name="product_id" value="{{ $product->id }}"><button class="ww-button ww-button-outline">Add to Wish List ♡</button></form><a href="{{ route('contact-page') }}">Ask an Expert</a></div></section>
<section class="ww-tabs"><div class="ww-tab-buttons" role="tablist" aria-label="Product information"><button id="ww-description-tab" role="tab" aria-selected="true" aria-controls="ww-description" data-tab="description">Description</button><button id="ww-reviews-tab" role="tab" aria-selected="false" aria-controls="ww-reviews" data-tab="reviews">Customer Reviews</button><button id="ww-shipping-tab" role="tab" aria-selected="false" aria-controls="ww-shipping" data-tab="shipping">Shipping + Return</button><button id="ww-info-tab" role="tab" aria-selected="false" aria-controls="ww-info" data-tab="info">Additional Information</button></div><div id="ww-description" data-tab-panel="description" role="tabpanel" aria-labelledby="ww-description-tab" class="ww-blog-body">{!! $product->long_description ?: nl2br(e($product->short_description)) !!}</div><div id="ww-reviews" data-tab-panel="reviews" role="tabpanel" aria-labelledby="ww-reviews-tab" hidden>@foreach(['review_success','review_error'] as $flash)@if(session($flash))<p class="ww-alert">{{ session($flash) }}</p>@endif @endforeach @forelse($product->approvedReviews as $review)<article class="ww-review"><h3>{{ $review->name ?: $review->user?->name ?: 'Customer' }}</h3><span class="ww-rating">{{ str_repeat('★',$review->rating) }}</span><p>{{ $review->review }}</p></article>@empty<p>No reviews yet. Be the first to review this watch.</p>@endforelse<h3 style="margin-top:30px">Write a Review</h3><form class="ww-review-form" action="{{ route('reviews.store',$product->id) }}" method="post">@csrf<label>Your Name<input name="name" value="{{ old('name',auth()->user()?->name) }}" required maxlength="255"></label><label>Email Address<input name="email" type="email" value="{{ old('email',auth()->user()?->email) }}" required maxlength="255"></label><label>Rating<select name="rating">@for($i=5;$i>=1;$i--)<option value="{{ $i }}">{{ $i }} stars</option>@endfor</select></label><label>Your Review<textarea name="review" rows="5" required minlength="10" maxlength="5000">{{ old('review') }}</textarea></label><button class="ww-button">Submit Review</button></form></div><div id="ww-shipping" data-tab-panel="shipping" role="tabpanel" aria-labelledby="ww-shipping-tab" hidden><h3>Shipping & Returns</h3><p>Delivery options and charges are shown at checkout. For returns, contact our customer service team with your order number.</p><a href="{{ route('contact-page') }}">Contact Us →</a></div><div id="ww-info" data-tab-panel="info" role="tabpanel" aria-labelledby="ww-info-tab" class="ww-blog-body" hidden>{!! $product->additional_info ?: '<p>For additional specifications, please contact our customer service team.</p>' !!}</div></section>
@if($relatedProducts->count())<section class="ww-section"><h2 class="ww-section-title">Related Products</h2><div class="ww-products">@foreach($relatedProducts as $product)@include('storefront.product-card')@endforeach</div></section>@endif</div>
@endsection

